#!/bin/bash

echo "🔍 Vérification du statut de connexion LinkedIn"
echo ""
echo "Méthode 1: Via l'interface web (RECOMMANDÉ)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ouvrez votre navigateur"
echo "2. Allez sur: http://localhost:3001/settings"
echo "3. Regardez la section 'Connexion LinkedIn (Obligatoire)'"
echo ""
echo "Si vous voyez:"
echo "  ✅ 'LinkedIn est connecté' → Votre compte est lié"
echo "  ❌ 'Se connecter à LinkedIn' → Votre compte n'est pas lié"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Méthode 2: Via l'API (nécessite un token)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Connectez-vous sur http://localhost:3001"
echo "2. Ouvrez la console (F12)"
echo "3. Tapez: localStorage.getItem('token')"
echo "4. Copiez le token"
echo "5. Exécutez: node check_linkedin_status.js <votre_token>"
echo ""
